### ISSUE TITLE
Sponsorship?

### ISSUE THREAD

**Issue by bs1180** [viennahtml/members#10]
A company I'm working with is looking for developers, and would like to sponsor the next meetup. Is this possible?

Obviously we build slightly more than static sites, but we like the mindset of picking the right tool for the job! The current adverts are [here](https://bdswiss.workable.com/).

**Comment by geraldb** [comment]
@bs1180 Hello, still the early days (for Vienna.html)  The next meetup is planned for (end-of) April. The idea would be to follow the model of the other user groups at sektor5 - that is, the sponsorship fee would  cover the drinks (still a small group e.g. 10+ or  something) so that would be Euro 50 or something if you're interested.   PS: You're of course welcome to prepare a talk - the format is about 10-20 minutes plus question time.   PPS: My "private" email is gerald.bauer@gmail.com

**Comment by bs1180** [comment]
Hi @geraldb - I thought there was a meetup on Tuesday?

**Comment by geraldb** [comment]
@bs1180  Yes, that's the 2nd meetup. It's all set and a little short notice e.g. not sure how to fit it into the website and how to handle payment (need to talk to sektor5 staff etc.)  However, you're welcome to drop by on Tuesday and arrange everything in person (e.g. announce you job openings and company sponsorship and pay the drinks - you will get a discount ;-)) . Cheers.

**Comment by bs1180** [comment]
Thanks @geraldb - I've sent you an email :+1:

**Comment by geraldb** [comment]
@bs1180 FYI: I'm closing the Vienna.html sponsorship ticket. Thousand thanks for your support and sponsorship. Will add a sponsorship section to the event page before the next meetup too and send out a tweet etc. Thanks again - we've got two great speakers for the next (last before the summer) Vienna.html meetup. Cheers.

**Comment by bs1180** [comment]
My pleasure, thanks @geraldb
